using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace WebProject.Migrations.AppDb
{
    /// <inheritdoc />
    public partial class LandTableCreating : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "IdentityUser",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    UserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NormalizedUserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NormalizedEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SecurityStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhoneNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "bit", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "bit", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IdentityUser", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "lands",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    IsOccupied = table.Column<bool>(type: "bit", nullable: false),
                    X = table.Column<int>(type: "int", nullable: false),
                    Y = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_lands", x => x.Id);
                    table.ForeignKey(
                        name: "FK_lands_IdentityUser_UserId",
                        column: x => x.UserId,
                        principalTable: "IdentityUser",
                        principalColumn: "Id");
                });

            migrationBuilder.InsertData(
                table: "lands",
                columns: new[] { "Id", "IsOccupied", "UserId", "X", "Y" },
                values: new object[,]
                {
                    { 1, false, null, 1, 1 },
                    { 2, false, null, 2, 1 },
                    { 3, false, null, 3, 1 },
                    { 4, false, null, 4, 1 },
                    { 5, false, null, 5, 1 },
                    { 6, false, null, 6, 1 },
                    { 7, false, null, 7, 1 },
                    { 8, false, null, 8, 1 },
                    { 9, false, null, 9, 1 },
                    { 10, false, null, 10, 1 },
                    { 11, false, null, 11, 1 },
                    { 12, false, null, 12, 1 },
                    { 13, false, null, 13, 1 },
                    { 14, false, null, 14, 1 },
                    { 15, false, null, 15, 1 },
                    { 16, false, null, 16, 1 },
                    { 17, false, null, 17, 1 },
                    { 18, false, null, 18, 1 },
                    { 19, false, null, 19, 1 },
                    { 20, false, null, 20, 1 },
                    { 21, false, null, 21, 1 },
                    { 22, false, null, 22, 1 },
                    { 23, false, null, 23, 1 },
                    { 24, false, null, 1, 2 },
                    { 25, false, null, 2, 2 },
                    { 26, false, null, 3, 2 },
                    { 27, false, null, 4, 2 },
                    { 28, false, null, 5, 2 },
                    { 29, false, null, 6, 2 },
                    { 30, false, null, 7, 2 },
                    { 31, false, null, 8, 2 },
                    { 32, false, null, 9, 2 },
                    { 33, false, null, 10, 2 },
                    { 34, false, null, 11, 2 },
                    { 35, false, null, 12, 2 },
                    { 36, false, null, 13, 2 },
                    { 37, false, null, 14, 2 },
                    { 38, false, null, 15, 2 },
                    { 39, false, null, 16, 2 },
                    { 40, false, null, 17, 2 },
                    { 41, false, null, 18, 2 },
                    { 42, false, null, 19, 2 },
                    { 43, false, null, 20, 2 },
                    { 44, false, null, 21, 2 },
                    { 45, false, null, 22, 2 },
                    { 46, false, null, 23, 2 },
                    { 47, false, null, 1, 3 },
                    { 48, false, null, 2, 3 },
                    { 49, false, null, 3, 3 },
                    { 50, false, null, 4, 3 },
                    { 51, false, null, 5, 3 },
                    { 52, false, null, 6, 3 },
                    { 53, false, null, 7, 3 },
                    { 54, false, null, 8, 3 },
                    { 55, false, null, 9, 3 },
                    { 56, false, null, 10, 3 },
                    { 57, false, null, 11, 3 },
                    { 58, false, null, 12, 3 },
                    { 59, false, null, 13, 3 },
                    { 60, false, null, 14, 3 },
                    { 61, false, null, 15, 3 },
                    { 62, false, null, 16, 3 },
                    { 63, false, null, 17, 3 },
                    { 64, false, null, 18, 3 },
                    { 65, false, null, 19, 3 },
                    { 66, false, null, 20, 3 },
                    { 67, false, null, 21, 3 },
                    { 68, false, null, 22, 3 },
                    { 69, false, null, 23, 3 },
                    { 70, false, null, 1, 4 },
                    { 71, false, null, 2, 4 },
                    { 72, false, null, 3, 4 },
                    { 73, false, null, 4, 4 },
                    { 74, false, null, 5, 4 },
                    { 75, false, null, 6, 4 },
                    { 76, false, null, 7, 4 },
                    { 77, false, null, 8, 4 },
                    { 78, false, null, 9, 4 },
                    { 79, false, null, 10, 4 },
                    { 80, false, null, 11, 4 },
                    { 81, false, null, 12, 4 },
                    { 82, false, null, 13, 4 },
                    { 83, false, null, 14, 4 },
                    { 84, false, null, 15, 4 },
                    { 85, false, null, 16, 4 },
                    { 86, false, null, 17, 4 },
                    { 87, false, null, 18, 4 },
                    { 88, false, null, 19, 4 },
                    { 89, false, null, 20, 4 },
                    { 90, false, null, 21, 4 },
                    { 91, false, null, 22, 4 },
                    { 92, false, null, 23, 4 },
                    { 93, false, null, 1, 5 },
                    { 94, false, null, 2, 5 },
                    { 95, false, null, 3, 5 },
                    { 96, false, null, 4, 5 },
                    { 97, false, null, 5, 5 },
                    { 98, false, null, 6, 5 },
                    { 99, false, null, 7, 5 },
                    { 100, false, null, 8, 5 },
                    { 101, false, null, 9, 5 },
                    { 102, false, null, 10, 5 },
                    { 103, false, null, 11, 5 },
                    { 104, false, null, 12, 5 },
                    { 105, false, null, 13, 5 },
                    { 106, false, null, 14, 5 },
                    { 107, false, null, 15, 5 },
                    { 108, false, null, 16, 5 },
                    { 109, false, null, 17, 5 },
                    { 110, false, null, 18, 5 },
                    { 111, false, null, 19, 5 },
                    { 112, false, null, 20, 5 },
                    { 113, false, null, 21, 5 },
                    { 114, false, null, 22, 5 },
                    { 115, false, null, 23, 5 },
                    { 116, false, null, 1, 6 },
                    { 117, false, null, 2, 6 },
                    { 118, false, null, 3, 6 },
                    { 119, false, null, 4, 6 },
                    { 120, false, null, 5, 6 },
                    { 121, false, null, 6, 6 },
                    { 122, false, null, 7, 6 },
                    { 123, false, null, 8, 6 },
                    { 124, false, null, 9, 6 },
                    { 125, false, null, 10, 6 },
                    { 126, false, null, 11, 6 },
                    { 127, false, null, 12, 6 },
                    { 128, false, null, 13, 6 },
                    { 129, false, null, 14, 6 },
                    { 130, false, null, 15, 6 },
                    { 131, false, null, 16, 6 },
                    { 132, false, null, 17, 6 },
                    { 133, false, null, 18, 6 },
                    { 134, false, null, 19, 6 },
                    { 135, false, null, 20, 6 },
                    { 136, false, null, 21, 6 },
                    { 137, false, null, 22, 6 },
                    { 138, false, null, 23, 6 },
                    { 139, false, null, 1, 7 },
                    { 140, false, null, 2, 7 },
                    { 141, false, null, 3, 7 },
                    { 142, false, null, 4, 7 },
                    { 143, false, null, 5, 7 },
                    { 144, false, null, 6, 7 },
                    { 145, false, null, 7, 7 },
                    { 146, false, null, 8, 7 },
                    { 147, false, null, 9, 7 },
                    { 148, false, null, 10, 7 },
                    { 149, false, null, 11, 7 },
                    { 150, false, null, 12, 7 },
                    { 151, false, null, 13, 7 },
                    { 152, false, null, 14, 7 },
                    { 153, false, null, 15, 7 },
                    { 154, false, null, 16, 7 },
                    { 155, false, null, 17, 7 },
                    { 156, false, null, 18, 7 },
                    { 157, false, null, 19, 7 },
                    { 158, false, null, 20, 7 },
                    { 159, false, null, 21, 7 },
                    { 160, false, null, 22, 7 },
                    { 161, false, null, 23, 7 },
                    { 162, false, null, 1, 8 },
                    { 163, false, null, 2, 8 },
                    { 164, false, null, 3, 8 },
                    { 165, false, null, 4, 8 },
                    { 166, false, null, 5, 8 },
                    { 167, false, null, 6, 8 },
                    { 168, false, null, 7, 8 },
                    { 169, false, null, 8, 8 },
                    { 170, false, null, 9, 8 },
                    { 171, false, null, 10, 8 },
                    { 172, false, null, 11, 8 },
                    { 173, false, null, 12, 8 },
                    { 174, false, null, 13, 8 },
                    { 175, false, null, 14, 8 },
                    { 176, false, null, 15, 8 },
                    { 177, false, null, 16, 8 },
                    { 178, false, null, 17, 8 },
                    { 179, false, null, 18, 8 },
                    { 180, false, null, 19, 8 },
                    { 181, false, null, 20, 8 },
                    { 182, false, null, 21, 8 },
                    { 183, false, null, 22, 8 },
                    { 184, false, null, 23, 8 },
                    { 185, false, null, 1, 9 },
                    { 186, false, null, 2, 9 },
                    { 187, false, null, 3, 9 },
                    { 188, false, null, 4, 9 },
                    { 189, false, null, 5, 9 },
                    { 190, false, null, 6, 9 },
                    { 191, false, null, 7, 9 },
                    { 192, false, null, 8, 9 },
                    { 193, false, null, 9, 9 },
                    { 194, false, null, 10, 9 },
                    { 195, false, null, 11, 9 },
                    { 196, false, null, 12, 9 },
                    { 197, false, null, 13, 9 },
                    { 198, false, null, 14, 9 },
                    { 199, false, null, 15, 9 },
                    { 200, false, null, 16, 9 },
                    { 201, false, null, 17, 9 },
                    { 202, false, null, 18, 9 },
                    { 203, false, null, 19, 9 },
                    { 204, false, null, 20, 9 },
                    { 205, false, null, 21, 9 },
                    { 206, false, null, 22, 9 },
                    { 207, false, null, 23, 9 },
                    { 208, false, null, 1, 10 },
                    { 209, false, null, 2, 10 },
                    { 210, false, null, 3, 10 },
                    { 211, false, null, 4, 10 },
                    { 212, false, null, 5, 10 },
                    { 213, false, null, 6, 10 },
                    { 214, false, null, 7, 10 },
                    { 215, false, null, 8, 10 },
                    { 216, false, null, 9, 10 },
                    { 217, false, null, 10, 10 },
                    { 218, false, null, 11, 10 },
                    { 219, false, null, 12, 10 },
                    { 220, false, null, 13, 10 },
                    { 221, false, null, 14, 10 },
                    { 222, false, null, 15, 10 },
                    { 223, false, null, 16, 10 },
                    { 224, false, null, 17, 10 },
                    { 225, false, null, 18, 10 },
                    { 226, false, null, 19, 10 },
                    { 227, false, null, 20, 10 },
                    { 228, false, null, 21, 10 },
                    { 229, false, null, 22, 10 },
                    { 230, false, null, 23, 10 },
                    { 231, false, null, 1, 11 },
                    { 232, false, null, 2, 11 },
                    { 233, false, null, 3, 11 },
                    { 234, false, null, 4, 11 },
                    { 235, false, null, 5, 11 },
                    { 236, false, null, 6, 11 },
                    { 237, false, null, 7, 11 },
                    { 238, false, null, 8, 11 },
                    { 239, false, null, 9, 11 },
                    { 240, false, null, 10, 11 },
                    { 241, false, null, 11, 11 },
                    { 242, false, null, 12, 11 },
                    { 243, false, null, 13, 11 },
                    { 244, false, null, 14, 11 },
                    { 245, false, null, 15, 11 },
                    { 246, false, null, 16, 11 },
                    { 247, false, null, 17, 11 },
                    { 248, false, null, 18, 11 },
                    { 249, false, null, 19, 11 },
                    { 250, false, null, 20, 11 },
                    { 251, false, null, 21, 11 },
                    { 252, false, null, 22, 11 },
                    { 253, false, null, 23, 11 },
                    { 254, false, null, 1, 12 },
                    { 255, false, null, 2, 12 },
                    { 256, false, null, 3, 12 },
                    { 257, false, null, 4, 12 },
                    { 258, false, null, 5, 12 },
                    { 259, false, null, 6, 12 },
                    { 260, false, null, 7, 12 },
                    { 261, false, null, 8, 12 },
                    { 262, false, null, 9, 12 },
                    { 263, false, null, 10, 12 },
                    { 264, false, null, 11, 12 },
                    { 265, false, null, 12, 12 },
                    { 266, false, null, 13, 12 },
                    { 267, false, null, 14, 12 },
                    { 268, false, null, 15, 12 },
                    { 269, false, null, 16, 12 },
                    { 270, false, null, 17, 12 },
                    { 271, false, null, 18, 12 },
                    { 272, false, null, 19, 12 },
                    { 273, false, null, 20, 12 },
                    { 274, false, null, 21, 12 },
                    { 275, false, null, 22, 12 },
                    { 276, false, null, 23, 12 },
                    { 277, false, null, 1, 13 },
                    { 278, false, null, 2, 13 },
                    { 279, false, null, 3, 13 },
                    { 280, false, null, 4, 13 },
                    { 281, false, null, 5, 13 },
                    { 282, false, null, 6, 13 },
                    { 283, false, null, 7, 13 },
                    { 284, false, null, 8, 13 },
                    { 285, false, null, 9, 13 },
                    { 286, false, null, 10, 13 },
                    { 287, false, null, 11, 13 },
                    { 288, false, null, 12, 13 },
                    { 289, false, null, 13, 13 },
                    { 290, false, null, 14, 13 },
                    { 291, false, null, 15, 13 },
                    { 292, false, null, 16, 13 },
                    { 293, false, null, 17, 13 },
                    { 294, false, null, 18, 13 },
                    { 295, false, null, 19, 13 },
                    { 296, false, null, 20, 13 },
                    { 297, false, null, 21, 13 },
                    { 298, false, null, 22, 13 },
                    { 299, false, null, 23, 13 },
                    { 300, false, null, 1, 14 },
                    { 301, false, null, 2, 14 },
                    { 302, false, null, 3, 14 },
                    { 303, false, null, 4, 14 },
                    { 304, false, null, 5, 14 },
                    { 305, false, null, 6, 14 },
                    { 306, false, null, 7, 14 },
                    { 307, false, null, 8, 14 },
                    { 308, false, null, 9, 14 },
                    { 309, false, null, 10, 14 },
                    { 310, false, null, 11, 14 },
                    { 311, false, null, 12, 14 },
                    { 312, false, null, 13, 14 },
                    { 313, false, null, 14, 14 },
                    { 314, false, null, 15, 14 },
                    { 315, false, null, 16, 14 },
                    { 316, false, null, 17, 14 },
                    { 317, false, null, 18, 14 },
                    { 318, false, null, 19, 14 },
                    { 319, false, null, 20, 14 },
                    { 320, false, null, 21, 14 },
                    { 321, false, null, 22, 14 },
                    { 322, false, null, 23, 14 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_lands_UserId",
                table: "lands",
                column: "UserId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "lands");

            migrationBuilder.DropTable(
                name: "IdentityUser");
        }
    }
}
