// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject.Models;

#nullable disable

namespace WebProject.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebProject.Models.Area", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AreaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "The first area"
                        });
                });

            modelBuilder.Entity("WebProject.Models.Land", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Lands");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 1
                        },
                        new
                        {
                            ID = 2,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 1
                        },
                        new
                        {
                            ID = 3,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 1
                        },
                        new
                        {
                            ID = 4,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 1
                        },
                        new
                        {
                            ID = 5,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 1
                        },
                        new
                        {
                            ID = 6,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 1
                        },
                        new
                        {
                            ID = 7,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 1
                        },
                        new
                        {
                            ID = 8,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 1
                        },
                        new
                        {
                            ID = 9,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 1
                        },
                        new
                        {
                            ID = 10,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 1
                        },
                        new
                        {
                            ID = 11,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 1
                        },
                        new
                        {
                            ID = 12,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 1
                        },
                        new
                        {
                            ID = 13,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 1
                        },
                        new
                        {
                            ID = 14,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 1
                        },
                        new
                        {
                            ID = 15,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 1
                        },
                        new
                        {
                            ID = 16,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 1
                        },
                        new
                        {
                            ID = 17,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 1
                        },
                        new
                        {
                            ID = 18,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 1
                        },
                        new
                        {
                            ID = 19,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 1
                        },
                        new
                        {
                            ID = 20,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 1
                        },
                        new
                        {
                            ID = 21,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 1
                        },
                        new
                        {
                            ID = 22,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 1
                        },
                        new
                        {
                            ID = 23,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 1
                        },
                        new
                        {
                            ID = 24,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 2
                        },
                        new
                        {
                            ID = 25,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 2
                        },
                        new
                        {
                            ID = 26,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 2
                        },
                        new
                        {
                            ID = 27,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 2
                        },
                        new
                        {
                            ID = 28,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 2
                        },
                        new
                        {
                            ID = 29,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 2
                        },
                        new
                        {
                            ID = 30,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 2
                        },
                        new
                        {
                            ID = 31,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 2
                        },
                        new
                        {
                            ID = 32,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 2
                        },
                        new
                        {
                            ID = 33,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 2
                        },
                        new
                        {
                            ID = 34,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 2
                        },
                        new
                        {
                            ID = 35,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 2
                        },
                        new
                        {
                            ID = 36,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 2
                        },
                        new
                        {
                            ID = 37,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 2
                        },
                        new
                        {
                            ID = 38,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 2
                        },
                        new
                        {
                            ID = 39,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 2
                        },
                        new
                        {
                            ID = 40,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 2
                        },
                        new
                        {
                            ID = 41,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 2
                        },
                        new
                        {
                            ID = 42,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 2
                        },
                        new
                        {
                            ID = 43,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 2
                        },
                        new
                        {
                            ID = 44,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 2
                        },
                        new
                        {
                            ID = 45,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 2
                        },
                        new
                        {
                            ID = 46,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 2
                        },
                        new
                        {
                            ID = 47,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 3
                        },
                        new
                        {
                            ID = 48,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 3
                        },
                        new
                        {
                            ID = 49,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 3
                        },
                        new
                        {
                            ID = 50,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 3
                        },
                        new
                        {
                            ID = 51,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 3
                        },
                        new
                        {
                            ID = 52,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 3
                        },
                        new
                        {
                            ID = 53,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 3
                        },
                        new
                        {
                            ID = 54,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 3
                        },
                        new
                        {
                            ID = 55,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 3
                        },
                        new
                        {
                            ID = 56,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 3
                        },
                        new
                        {
                            ID = 57,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 3
                        },
                        new
                        {
                            ID = 58,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 3
                        },
                        new
                        {
                            ID = 59,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 3
                        },
                        new
                        {
                            ID = 60,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 3
                        },
                        new
                        {
                            ID = 61,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 3
                        },
                        new
                        {
                            ID = 62,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 3
                        },
                        new
                        {
                            ID = 63,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 3
                        },
                        new
                        {
                            ID = 64,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 3
                        },
                        new
                        {
                            ID = 65,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 3
                        },
                        new
                        {
                            ID = 66,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 3
                        },
                        new
                        {
                            ID = 67,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 3
                        },
                        new
                        {
                            ID = 68,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 3
                        },
                        new
                        {
                            ID = 69,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 3
                        },
                        new
                        {
                            ID = 70,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 4
                        },
                        new
                        {
                            ID = 71,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 4
                        },
                        new
                        {
                            ID = 72,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 4
                        },
                        new
                        {
                            ID = 73,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 4
                        },
                        new
                        {
                            ID = 74,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 4
                        },
                        new
                        {
                            ID = 75,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 4
                        },
                        new
                        {
                            ID = 76,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 4
                        },
                        new
                        {
                            ID = 77,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 4
                        },
                        new
                        {
                            ID = 78,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 4
                        },
                        new
                        {
                            ID = 79,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 4
                        },
                        new
                        {
                            ID = 80,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 4
                        },
                        new
                        {
                            ID = 81,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 4
                        },
                        new
                        {
                            ID = 82,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 4
                        },
                        new
                        {
                            ID = 83,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 4
                        },
                        new
                        {
                            ID = 84,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 4
                        },
                        new
                        {
                            ID = 85,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 4
                        },
                        new
                        {
                            ID = 86,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 4
                        },
                        new
                        {
                            ID = 87,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 4
                        },
                        new
                        {
                            ID = 88,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 4
                        },
                        new
                        {
                            ID = 89,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 4
                        },
                        new
                        {
                            ID = 90,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 4
                        },
                        new
                        {
                            ID = 91,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 4
                        },
                        new
                        {
                            ID = 92,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 4
                        },
                        new
                        {
                            ID = 93,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 5
                        },
                        new
                        {
                            ID = 94,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 5
                        },
                        new
                        {
                            ID = 95,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 5
                        },
                        new
                        {
                            ID = 96,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 5
                        },
                        new
                        {
                            ID = 97,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 5
                        },
                        new
                        {
                            ID = 98,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 5
                        },
                        new
                        {
                            ID = 99,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 5
                        },
                        new
                        {
                            ID = 100,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 5
                        },
                        new
                        {
                            ID = 101,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 5
                        },
                        new
                        {
                            ID = 102,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 5
                        },
                        new
                        {
                            ID = 103,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 5
                        },
                        new
                        {
                            ID = 104,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 5
                        },
                        new
                        {
                            ID = 105,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 5
                        },
                        new
                        {
                            ID = 106,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 5
                        },
                        new
                        {
                            ID = 107,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 5
                        },
                        new
                        {
                            ID = 108,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 5
                        },
                        new
                        {
                            ID = 109,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 5
                        },
                        new
                        {
                            ID = 110,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 5
                        },
                        new
                        {
                            ID = 111,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 5
                        },
                        new
                        {
                            ID = 112,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 5
                        },
                        new
                        {
                            ID = 113,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 5
                        },
                        new
                        {
                            ID = 114,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 5
                        },
                        new
                        {
                            ID = 115,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 5
                        },
                        new
                        {
                            ID = 116,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 6
                        },
                        new
                        {
                            ID = 117,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 6
                        },
                        new
                        {
                            ID = 118,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 6
                        },
                        new
                        {
                            ID = 119,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 6
                        },
                        new
                        {
                            ID = 120,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 6
                        },
                        new
                        {
                            ID = 121,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 6
                        },
                        new
                        {
                            ID = 122,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 6
                        },
                        new
                        {
                            ID = 123,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 6
                        },
                        new
                        {
                            ID = 124,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 6
                        },
                        new
                        {
                            ID = 125,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 6
                        },
                        new
                        {
                            ID = 126,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 6
                        },
                        new
                        {
                            ID = 127,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 6
                        },
                        new
                        {
                            ID = 128,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 6
                        },
                        new
                        {
                            ID = 129,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 6
                        },
                        new
                        {
                            ID = 130,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 6
                        },
                        new
                        {
                            ID = 131,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 6
                        },
                        new
                        {
                            ID = 132,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 6
                        },
                        new
                        {
                            ID = 133,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 6
                        },
                        new
                        {
                            ID = 134,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 6
                        },
                        new
                        {
                            ID = 135,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 6
                        },
                        new
                        {
                            ID = 136,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 6
                        },
                        new
                        {
                            ID = 137,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 6
                        },
                        new
                        {
                            ID = 138,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 6
                        },
                        new
                        {
                            ID = 139,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 7
                        },
                        new
                        {
                            ID = 140,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 7
                        },
                        new
                        {
                            ID = 141,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 7
                        },
                        new
                        {
                            ID = 142,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 7
                        },
                        new
                        {
                            ID = 143,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 7
                        },
                        new
                        {
                            ID = 144,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 7
                        },
                        new
                        {
                            ID = 145,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 7
                        },
                        new
                        {
                            ID = 146,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 7
                        },
                        new
                        {
                            ID = 147,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 7
                        },
                        new
                        {
                            ID = 148,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 7
                        },
                        new
                        {
                            ID = 149,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 7
                        },
                        new
                        {
                            ID = 150,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 7
                        },
                        new
                        {
                            ID = 151,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 7
                        },
                        new
                        {
                            ID = 152,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 7
                        },
                        new
                        {
                            ID = 153,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 7
                        },
                        new
                        {
                            ID = 154,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 7
                        },
                        new
                        {
                            ID = 155,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 7
                        },
                        new
                        {
                            ID = 156,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 7
                        },
                        new
                        {
                            ID = 157,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 7
                        },
                        new
                        {
                            ID = 158,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 7
                        },
                        new
                        {
                            ID = 159,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 7
                        },
                        new
                        {
                            ID = 160,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 7
                        },
                        new
                        {
                            ID = 161,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 7
                        },
                        new
                        {
                            ID = 162,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 8
                        },
                        new
                        {
                            ID = 163,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 8
                        },
                        new
                        {
                            ID = 164,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 8
                        },
                        new
                        {
                            ID = 165,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 8
                        },
                        new
                        {
                            ID = 166,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 8
                        },
                        new
                        {
                            ID = 167,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 8
                        },
                        new
                        {
                            ID = 168,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 8
                        },
                        new
                        {
                            ID = 169,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 8
                        },
                        new
                        {
                            ID = 170,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 8
                        },
                        new
                        {
                            ID = 171,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 8
                        },
                        new
                        {
                            ID = 172,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 8
                        },
                        new
                        {
                            ID = 173,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 8
                        },
                        new
                        {
                            ID = 174,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 8
                        },
                        new
                        {
                            ID = 175,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 8
                        },
                        new
                        {
                            ID = 176,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 8
                        },
                        new
                        {
                            ID = 177,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 8
                        },
                        new
                        {
                            ID = 178,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 8
                        },
                        new
                        {
                            ID = 179,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 8
                        },
                        new
                        {
                            ID = 180,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 8
                        },
                        new
                        {
                            ID = 181,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 8
                        },
                        new
                        {
                            ID = 182,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 8
                        },
                        new
                        {
                            ID = 183,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 8
                        },
                        new
                        {
                            ID = 184,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 8
                        },
                        new
                        {
                            ID = 185,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 9
                        },
                        new
                        {
                            ID = 186,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 9
                        },
                        new
                        {
                            ID = 187,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 9
                        },
                        new
                        {
                            ID = 188,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 9
                        },
                        new
                        {
                            ID = 189,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 9
                        },
                        new
                        {
                            ID = 190,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 9
                        },
                        new
                        {
                            ID = 191,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 9
                        },
                        new
                        {
                            ID = 192,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 9
                        },
                        new
                        {
                            ID = 193,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 9
                        },
                        new
                        {
                            ID = 194,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 9
                        },
                        new
                        {
                            ID = 195,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 9
                        },
                        new
                        {
                            ID = 196,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 9
                        },
                        new
                        {
                            ID = 197,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 9
                        },
                        new
                        {
                            ID = 198,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 9
                        },
                        new
                        {
                            ID = 199,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 9
                        },
                        new
                        {
                            ID = 200,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 9
                        },
                        new
                        {
                            ID = 201,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 9
                        },
                        new
                        {
                            ID = 202,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 9
                        },
                        new
                        {
                            ID = 203,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 9
                        },
                        new
                        {
                            ID = 204,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 9
                        },
                        new
                        {
                            ID = 205,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 9
                        },
                        new
                        {
                            ID = 206,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 9
                        },
                        new
                        {
                            ID = 207,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 9
                        },
                        new
                        {
                            ID = 208,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 10
                        },
                        new
                        {
                            ID = 209,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 10
                        },
                        new
                        {
                            ID = 210,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 10
                        },
                        new
                        {
                            ID = 211,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 10
                        },
                        new
                        {
                            ID = 212,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 10
                        },
                        new
                        {
                            ID = 213,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 10
                        },
                        new
                        {
                            ID = 214,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 10
                        },
                        new
                        {
                            ID = 215,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 10
                        },
                        new
                        {
                            ID = 216,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 10
                        },
                        new
                        {
                            ID = 217,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 10
                        },
                        new
                        {
                            ID = 218,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 10
                        },
                        new
                        {
                            ID = 219,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 10
                        },
                        new
                        {
                            ID = 220,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 10
                        },
                        new
                        {
                            ID = 221,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 10
                        },
                        new
                        {
                            ID = 222,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 10
                        },
                        new
                        {
                            ID = 223,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 10
                        },
                        new
                        {
                            ID = 224,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 10
                        },
                        new
                        {
                            ID = 225,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 10
                        },
                        new
                        {
                            ID = 226,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 10
                        },
                        new
                        {
                            ID = 227,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 10
                        },
                        new
                        {
                            ID = 228,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 10
                        },
                        new
                        {
                            ID = 229,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 10
                        },
                        new
                        {
                            ID = 230,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 10
                        },
                        new
                        {
                            ID = 231,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 11
                        },
                        new
                        {
                            ID = 232,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 11
                        },
                        new
                        {
                            ID = 233,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 11
                        },
                        new
                        {
                            ID = 234,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 11
                        },
                        new
                        {
                            ID = 235,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 11
                        },
                        new
                        {
                            ID = 236,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 11
                        },
                        new
                        {
                            ID = 237,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 11
                        },
                        new
                        {
                            ID = 238,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 11
                        },
                        new
                        {
                            ID = 239,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 11
                        },
                        new
                        {
                            ID = 240,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 11
                        },
                        new
                        {
                            ID = 241,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 11
                        },
                        new
                        {
                            ID = 242,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 11
                        },
                        new
                        {
                            ID = 243,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 11
                        },
                        new
                        {
                            ID = 244,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 11
                        },
                        new
                        {
                            ID = 245,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 11
                        },
                        new
                        {
                            ID = 246,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 11
                        },
                        new
                        {
                            ID = 247,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 11
                        },
                        new
                        {
                            ID = 248,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 11
                        },
                        new
                        {
                            ID = 249,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 11
                        },
                        new
                        {
                            ID = 250,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 11
                        },
                        new
                        {
                            ID = 251,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 11
                        },
                        new
                        {
                            ID = 252,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 11
                        },
                        new
                        {
                            ID = 253,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 11
                        },
                        new
                        {
                            ID = 254,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 12
                        },
                        new
                        {
                            ID = 255,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 12
                        },
                        new
                        {
                            ID = 256,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 12
                        },
                        new
                        {
                            ID = 257,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 12
                        },
                        new
                        {
                            ID = 258,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 12
                        },
                        new
                        {
                            ID = 259,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 12
                        },
                        new
                        {
                            ID = 260,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 12
                        },
                        new
                        {
                            ID = 261,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 12
                        },
                        new
                        {
                            ID = 262,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 12
                        },
                        new
                        {
                            ID = 263,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 12
                        },
                        new
                        {
                            ID = 264,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 12
                        },
                        new
                        {
                            ID = 265,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 12
                        },
                        new
                        {
                            ID = 266,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 12
                        },
                        new
                        {
                            ID = 267,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 12
                        },
                        new
                        {
                            ID = 268,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 12
                        },
                        new
                        {
                            ID = 269,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 12
                        },
                        new
                        {
                            ID = 270,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 12
                        },
                        new
                        {
                            ID = 271,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 12
                        },
                        new
                        {
                            ID = 272,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 12
                        },
                        new
                        {
                            ID = 273,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 12
                        },
                        new
                        {
                            ID = 274,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 12
                        },
                        new
                        {
                            ID = 275,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 12
                        },
                        new
                        {
                            ID = 276,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 12
                        },
                        new
                        {
                            ID = 277,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 13
                        },
                        new
                        {
                            ID = 278,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 13
                        },
                        new
                        {
                            ID = 279,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 13
                        },
                        new
                        {
                            ID = 280,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 13
                        },
                        new
                        {
                            ID = 281,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 13
                        },
                        new
                        {
                            ID = 282,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 13
                        },
                        new
                        {
                            ID = 283,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 13
                        },
                        new
                        {
                            ID = 284,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 13
                        },
                        new
                        {
                            ID = 285,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 13
                        },
                        new
                        {
                            ID = 286,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 13
                        },
                        new
                        {
                            ID = 287,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 13
                        },
                        new
                        {
                            ID = 288,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 13
                        },
                        new
                        {
                            ID = 289,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 13
                        },
                        new
                        {
                            ID = 290,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 13
                        },
                        new
                        {
                            ID = 291,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 13
                        },
                        new
                        {
                            ID = 292,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 13
                        },
                        new
                        {
                            ID = 293,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 13
                        },
                        new
                        {
                            ID = 294,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 13
                        },
                        new
                        {
                            ID = 295,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 13
                        },
                        new
                        {
                            ID = 296,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 13
                        },
                        new
                        {
                            ID = 297,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 13
                        },
                        new
                        {
                            ID = 298,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 13
                        },
                        new
                        {
                            ID = 299,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 13
                        },
                        new
                        {
                            ID = 300,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 14
                        },
                        new
                        {
                            ID = 301,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 2,
                            Y = 14
                        },
                        new
                        {
                            ID = 302,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 3,
                            Y = 14
                        },
                        new
                        {
                            ID = 303,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 4,
                            Y = 14
                        },
                        new
                        {
                            ID = 304,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 5,
                            Y = 14
                        },
                        new
                        {
                            ID = 305,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 6,
                            Y = 14
                        },
                        new
                        {
                            ID = 306,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 7,
                            Y = 14
                        },
                        new
                        {
                            ID = 307,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 8,
                            Y = 14
                        },
                        new
                        {
                            ID = 308,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 9,
                            Y = 14
                        },
                        new
                        {
                            ID = 309,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 10,
                            Y = 14
                        },
                        new
                        {
                            ID = 310,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 11,
                            Y = 14
                        },
                        new
                        {
                            ID = 311,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 12,
                            Y = 14
                        },
                        new
                        {
                            ID = 312,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 13,
                            Y = 14
                        },
                        new
                        {
                            ID = 313,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 14,
                            Y = 14
                        },
                        new
                        {
                            ID = 314,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 15,
                            Y = 14
                        },
                        new
                        {
                            ID = 315,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 16,
                            Y = 14
                        },
                        new
                        {
                            ID = 316,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 17,
                            Y = 14
                        },
                        new
                        {
                            ID = 317,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 18,
                            Y = 14
                        },
                        new
                        {
                            ID = 318,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 19,
                            Y = 14
                        },
                        new
                        {
                            ID = 319,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 20,
                            Y = 14
                        },
                        new
                        {
                            ID = 320,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 21,
                            Y = 14
                        },
                        new
                        {
                            ID = 321,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 22,
                            Y = 14
                        },
                        new
                        {
                            ID = 322,
                            AreaId = 1,
                            IsOccupied = false,
                            X = 23,
                            Y = 14
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
