// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject.Models;

#nullable disable

namespace WebProject.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("WebProject.Models.Land", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("lands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            X = 1,
                            Y = 1
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            X = 2,
                            Y = 1
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            X = 3,
                            Y = 1
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            X = 4,
                            Y = 1
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            X = 5,
                            Y = 1
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            X = 6,
                            Y = 1
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            X = 7,
                            Y = 1
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            X = 8,
                            Y = 1
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            X = 9,
                            Y = 1
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            X = 10,
                            Y = 1
                        },
                        new
                        {
                            Id = 11,
                            IsOccupied = false,
                            X = 11,
                            Y = 1
                        },
                        new
                        {
                            Id = 12,
                            IsOccupied = false,
                            X = 12,
                            Y = 1
                        },
                        new
                        {
                            Id = 13,
                            IsOccupied = false,
                            X = 13,
                            Y = 1
                        },
                        new
                        {
                            Id = 14,
                            IsOccupied = false,
                            X = 14,
                            Y = 1
                        },
                        new
                        {
                            Id = 15,
                            IsOccupied = false,
                            X = 15,
                            Y = 1
                        },
                        new
                        {
                            Id = 16,
                            IsOccupied = false,
                            X = 16,
                            Y = 1
                        },
                        new
                        {
                            Id = 17,
                            IsOccupied = false,
                            X = 17,
                            Y = 1
                        },
                        new
                        {
                            Id = 18,
                            IsOccupied = false,
                            X = 18,
                            Y = 1
                        },
                        new
                        {
                            Id = 19,
                            IsOccupied = false,
                            X = 19,
                            Y = 1
                        },
                        new
                        {
                            Id = 20,
                            IsOccupied = false,
                            X = 20,
                            Y = 1
                        },
                        new
                        {
                            Id = 21,
                            IsOccupied = false,
                            X = 21,
                            Y = 1
                        },
                        new
                        {
                            Id = 22,
                            IsOccupied = false,
                            X = 22,
                            Y = 1
                        },
                        new
                        {
                            Id = 23,
                            IsOccupied = false,
                            X = 23,
                            Y = 1
                        },
                        new
                        {
                            Id = 24,
                            IsOccupied = false,
                            X = 1,
                            Y = 2
                        },
                        new
                        {
                            Id = 25,
                            IsOccupied = false,
                            X = 2,
                            Y = 2
                        },
                        new
                        {
                            Id = 26,
                            IsOccupied = false,
                            X = 3,
                            Y = 2
                        },
                        new
                        {
                            Id = 27,
                            IsOccupied = false,
                            X = 4,
                            Y = 2
                        },
                        new
                        {
                            Id = 28,
                            IsOccupied = false,
                            X = 5,
                            Y = 2
                        },
                        new
                        {
                            Id = 29,
                            IsOccupied = false,
                            X = 6,
                            Y = 2
                        },
                        new
                        {
                            Id = 30,
                            IsOccupied = false,
                            X = 7,
                            Y = 2
                        },
                        new
                        {
                            Id = 31,
                            IsOccupied = false,
                            X = 8,
                            Y = 2
                        },
                        new
                        {
                            Id = 32,
                            IsOccupied = false,
                            X = 9,
                            Y = 2
                        },
                        new
                        {
                            Id = 33,
                            IsOccupied = false,
                            X = 10,
                            Y = 2
                        },
                        new
                        {
                            Id = 34,
                            IsOccupied = false,
                            X = 11,
                            Y = 2
                        },
                        new
                        {
                            Id = 35,
                            IsOccupied = false,
                            X = 12,
                            Y = 2
                        },
                        new
                        {
                            Id = 36,
                            IsOccupied = false,
                            X = 13,
                            Y = 2
                        },
                        new
                        {
                            Id = 37,
                            IsOccupied = false,
                            X = 14,
                            Y = 2
                        },
                        new
                        {
                            Id = 38,
                            IsOccupied = false,
                            X = 15,
                            Y = 2
                        },
                        new
                        {
                            Id = 39,
                            IsOccupied = false,
                            X = 16,
                            Y = 2
                        },
                        new
                        {
                            Id = 40,
                            IsOccupied = false,
                            X = 17,
                            Y = 2
                        },
                        new
                        {
                            Id = 41,
                            IsOccupied = false,
                            X = 18,
                            Y = 2
                        },
                        new
                        {
                            Id = 42,
                            IsOccupied = false,
                            X = 19,
                            Y = 2
                        },
                        new
                        {
                            Id = 43,
                            IsOccupied = false,
                            X = 20,
                            Y = 2
                        },
                        new
                        {
                            Id = 44,
                            IsOccupied = false,
                            X = 21,
                            Y = 2
                        },
                        new
                        {
                            Id = 45,
                            IsOccupied = false,
                            X = 22,
                            Y = 2
                        },
                        new
                        {
                            Id = 46,
                            IsOccupied = false,
                            X = 23,
                            Y = 2
                        },
                        new
                        {
                            Id = 47,
                            IsOccupied = false,
                            X = 1,
                            Y = 3
                        },
                        new
                        {
                            Id = 48,
                            IsOccupied = false,
                            X = 2,
                            Y = 3
                        },
                        new
                        {
                            Id = 49,
                            IsOccupied = false,
                            X = 3,
                            Y = 3
                        },
                        new
                        {
                            Id = 50,
                            IsOccupied = false,
                            X = 4,
                            Y = 3
                        },
                        new
                        {
                            Id = 51,
                            IsOccupied = false,
                            X = 5,
                            Y = 3
                        },
                        new
                        {
                            Id = 52,
                            IsOccupied = false,
                            X = 6,
                            Y = 3
                        },
                        new
                        {
                            Id = 53,
                            IsOccupied = false,
                            X = 7,
                            Y = 3
                        },
                        new
                        {
                            Id = 54,
                            IsOccupied = false,
                            X = 8,
                            Y = 3
                        },
                        new
                        {
                            Id = 55,
                            IsOccupied = false,
                            X = 9,
                            Y = 3
                        },
                        new
                        {
                            Id = 56,
                            IsOccupied = false,
                            X = 10,
                            Y = 3
                        },
                        new
                        {
                            Id = 57,
                            IsOccupied = false,
                            X = 11,
                            Y = 3
                        },
                        new
                        {
                            Id = 58,
                            IsOccupied = false,
                            X = 12,
                            Y = 3
                        },
                        new
                        {
                            Id = 59,
                            IsOccupied = false,
                            X = 13,
                            Y = 3
                        },
                        new
                        {
                            Id = 60,
                            IsOccupied = false,
                            X = 14,
                            Y = 3
                        },
                        new
                        {
                            Id = 61,
                            IsOccupied = false,
                            X = 15,
                            Y = 3
                        },
                        new
                        {
                            Id = 62,
                            IsOccupied = false,
                            X = 16,
                            Y = 3
                        },
                        new
                        {
                            Id = 63,
                            IsOccupied = false,
                            X = 17,
                            Y = 3
                        },
                        new
                        {
                            Id = 64,
                            IsOccupied = false,
                            X = 18,
                            Y = 3
                        },
                        new
                        {
                            Id = 65,
                            IsOccupied = false,
                            X = 19,
                            Y = 3
                        },
                        new
                        {
                            Id = 66,
                            IsOccupied = false,
                            X = 20,
                            Y = 3
                        },
                        new
                        {
                            Id = 67,
                            IsOccupied = false,
                            X = 21,
                            Y = 3
                        },
                        new
                        {
                            Id = 68,
                            IsOccupied = false,
                            X = 22,
                            Y = 3
                        },
                        new
                        {
                            Id = 69,
                            IsOccupied = false,
                            X = 23,
                            Y = 3
                        },
                        new
                        {
                            Id = 70,
                            IsOccupied = false,
                            X = 1,
                            Y = 4
                        },
                        new
                        {
                            Id = 71,
                            IsOccupied = false,
                            X = 2,
                            Y = 4
                        },
                        new
                        {
                            Id = 72,
                            IsOccupied = false,
                            X = 3,
                            Y = 4
                        },
                        new
                        {
                            Id = 73,
                            IsOccupied = false,
                            X = 4,
                            Y = 4
                        },
                        new
                        {
                            Id = 74,
                            IsOccupied = false,
                            X = 5,
                            Y = 4
                        },
                        new
                        {
                            Id = 75,
                            IsOccupied = false,
                            X = 6,
                            Y = 4
                        },
                        new
                        {
                            Id = 76,
                            IsOccupied = false,
                            X = 7,
                            Y = 4
                        },
                        new
                        {
                            Id = 77,
                            IsOccupied = false,
                            X = 8,
                            Y = 4
                        },
                        new
                        {
                            Id = 78,
                            IsOccupied = false,
                            X = 9,
                            Y = 4
                        },
                        new
                        {
                            Id = 79,
                            IsOccupied = false,
                            X = 10,
                            Y = 4
                        },
                        new
                        {
                            Id = 80,
                            IsOccupied = false,
                            X = 11,
                            Y = 4
                        },
                        new
                        {
                            Id = 81,
                            IsOccupied = false,
                            X = 12,
                            Y = 4
                        },
                        new
                        {
                            Id = 82,
                            IsOccupied = false,
                            X = 13,
                            Y = 4
                        },
                        new
                        {
                            Id = 83,
                            IsOccupied = false,
                            X = 14,
                            Y = 4
                        },
                        new
                        {
                            Id = 84,
                            IsOccupied = false,
                            X = 15,
                            Y = 4
                        },
                        new
                        {
                            Id = 85,
                            IsOccupied = false,
                            X = 16,
                            Y = 4
                        },
                        new
                        {
                            Id = 86,
                            IsOccupied = false,
                            X = 17,
                            Y = 4
                        },
                        new
                        {
                            Id = 87,
                            IsOccupied = false,
                            X = 18,
                            Y = 4
                        },
                        new
                        {
                            Id = 88,
                            IsOccupied = false,
                            X = 19,
                            Y = 4
                        },
                        new
                        {
                            Id = 89,
                            IsOccupied = false,
                            X = 20,
                            Y = 4
                        },
                        new
                        {
                            Id = 90,
                            IsOccupied = false,
                            X = 21,
                            Y = 4
                        },
                        new
                        {
                            Id = 91,
                            IsOccupied = false,
                            X = 22,
                            Y = 4
                        },
                        new
                        {
                            Id = 92,
                            IsOccupied = false,
                            X = 23,
                            Y = 4
                        },
                        new
                        {
                            Id = 93,
                            IsOccupied = false,
                            X = 1,
                            Y = 5
                        },
                        new
                        {
                            Id = 94,
                            IsOccupied = false,
                            X = 2,
                            Y = 5
                        },
                        new
                        {
                            Id = 95,
                            IsOccupied = false,
                            X = 3,
                            Y = 5
                        },
                        new
                        {
                            Id = 96,
                            IsOccupied = false,
                            X = 4,
                            Y = 5
                        },
                        new
                        {
                            Id = 97,
                            IsOccupied = false,
                            X = 5,
                            Y = 5
                        },
                        new
                        {
                            Id = 98,
                            IsOccupied = false,
                            X = 6,
                            Y = 5
                        },
                        new
                        {
                            Id = 99,
                            IsOccupied = false,
                            X = 7,
                            Y = 5
                        },
                        new
                        {
                            Id = 100,
                            IsOccupied = false,
                            X = 8,
                            Y = 5
                        },
                        new
                        {
                            Id = 101,
                            IsOccupied = false,
                            X = 9,
                            Y = 5
                        },
                        new
                        {
                            Id = 102,
                            IsOccupied = false,
                            X = 10,
                            Y = 5
                        },
                        new
                        {
                            Id = 103,
                            IsOccupied = false,
                            X = 11,
                            Y = 5
                        },
                        new
                        {
                            Id = 104,
                            IsOccupied = false,
                            X = 12,
                            Y = 5
                        },
                        new
                        {
                            Id = 105,
                            IsOccupied = false,
                            X = 13,
                            Y = 5
                        },
                        new
                        {
                            Id = 106,
                            IsOccupied = false,
                            X = 14,
                            Y = 5
                        },
                        new
                        {
                            Id = 107,
                            IsOccupied = false,
                            X = 15,
                            Y = 5
                        },
                        new
                        {
                            Id = 108,
                            IsOccupied = false,
                            X = 16,
                            Y = 5
                        },
                        new
                        {
                            Id = 109,
                            IsOccupied = false,
                            X = 17,
                            Y = 5
                        },
                        new
                        {
                            Id = 110,
                            IsOccupied = false,
                            X = 18,
                            Y = 5
                        },
                        new
                        {
                            Id = 111,
                            IsOccupied = false,
                            X = 19,
                            Y = 5
                        },
                        new
                        {
                            Id = 112,
                            IsOccupied = false,
                            X = 20,
                            Y = 5
                        },
                        new
                        {
                            Id = 113,
                            IsOccupied = false,
                            X = 21,
                            Y = 5
                        },
                        new
                        {
                            Id = 114,
                            IsOccupied = false,
                            X = 22,
                            Y = 5
                        },
                        new
                        {
                            Id = 115,
                            IsOccupied = false,
                            X = 23,
                            Y = 5
                        },
                        new
                        {
                            Id = 116,
                            IsOccupied = false,
                            X = 1,
                            Y = 6
                        },
                        new
                        {
                            Id = 117,
                            IsOccupied = false,
                            X = 2,
                            Y = 6
                        },
                        new
                        {
                            Id = 118,
                            IsOccupied = false,
                            X = 3,
                            Y = 6
                        },
                        new
                        {
                            Id = 119,
                            IsOccupied = false,
                            X = 4,
                            Y = 6
                        },
                        new
                        {
                            Id = 120,
                            IsOccupied = false,
                            X = 5,
                            Y = 6
                        },
                        new
                        {
                            Id = 121,
                            IsOccupied = false,
                            X = 6,
                            Y = 6
                        },
                        new
                        {
                            Id = 122,
                            IsOccupied = false,
                            X = 7,
                            Y = 6
                        },
                        new
                        {
                            Id = 123,
                            IsOccupied = false,
                            X = 8,
                            Y = 6
                        },
                        new
                        {
                            Id = 124,
                            IsOccupied = false,
                            X = 9,
                            Y = 6
                        },
                        new
                        {
                            Id = 125,
                            IsOccupied = false,
                            X = 10,
                            Y = 6
                        },
                        new
                        {
                            Id = 126,
                            IsOccupied = false,
                            X = 11,
                            Y = 6
                        },
                        new
                        {
                            Id = 127,
                            IsOccupied = false,
                            X = 12,
                            Y = 6
                        },
                        new
                        {
                            Id = 128,
                            IsOccupied = false,
                            X = 13,
                            Y = 6
                        },
                        new
                        {
                            Id = 129,
                            IsOccupied = false,
                            X = 14,
                            Y = 6
                        },
                        new
                        {
                            Id = 130,
                            IsOccupied = false,
                            X = 15,
                            Y = 6
                        },
                        new
                        {
                            Id = 131,
                            IsOccupied = false,
                            X = 16,
                            Y = 6
                        },
                        new
                        {
                            Id = 132,
                            IsOccupied = false,
                            X = 17,
                            Y = 6
                        },
                        new
                        {
                            Id = 133,
                            IsOccupied = false,
                            X = 18,
                            Y = 6
                        },
                        new
                        {
                            Id = 134,
                            IsOccupied = false,
                            X = 19,
                            Y = 6
                        },
                        new
                        {
                            Id = 135,
                            IsOccupied = false,
                            X = 20,
                            Y = 6
                        },
                        new
                        {
                            Id = 136,
                            IsOccupied = false,
                            X = 21,
                            Y = 6
                        },
                        new
                        {
                            Id = 137,
                            IsOccupied = false,
                            X = 22,
                            Y = 6
                        },
                        new
                        {
                            Id = 138,
                            IsOccupied = false,
                            X = 23,
                            Y = 6
                        },
                        new
                        {
                            Id = 139,
                            IsOccupied = false,
                            X = 1,
                            Y = 7
                        },
                        new
                        {
                            Id = 140,
                            IsOccupied = false,
                            X = 2,
                            Y = 7
                        },
                        new
                        {
                            Id = 141,
                            IsOccupied = false,
                            X = 3,
                            Y = 7
                        },
                        new
                        {
                            Id = 142,
                            IsOccupied = false,
                            X = 4,
                            Y = 7
                        },
                        new
                        {
                            Id = 143,
                            IsOccupied = false,
                            X = 5,
                            Y = 7
                        },
                        new
                        {
                            Id = 144,
                            IsOccupied = false,
                            X = 6,
                            Y = 7
                        },
                        new
                        {
                            Id = 145,
                            IsOccupied = false,
                            X = 7,
                            Y = 7
                        },
                        new
                        {
                            Id = 146,
                            IsOccupied = false,
                            X = 8,
                            Y = 7
                        },
                        new
                        {
                            Id = 147,
                            IsOccupied = false,
                            X = 9,
                            Y = 7
                        },
                        new
                        {
                            Id = 148,
                            IsOccupied = false,
                            X = 10,
                            Y = 7
                        },
                        new
                        {
                            Id = 149,
                            IsOccupied = false,
                            X = 11,
                            Y = 7
                        },
                        new
                        {
                            Id = 150,
                            IsOccupied = false,
                            X = 12,
                            Y = 7
                        },
                        new
                        {
                            Id = 151,
                            IsOccupied = false,
                            X = 13,
                            Y = 7
                        },
                        new
                        {
                            Id = 152,
                            IsOccupied = false,
                            X = 14,
                            Y = 7
                        },
                        new
                        {
                            Id = 153,
                            IsOccupied = false,
                            X = 15,
                            Y = 7
                        },
                        new
                        {
                            Id = 154,
                            IsOccupied = false,
                            X = 16,
                            Y = 7
                        },
                        new
                        {
                            Id = 155,
                            IsOccupied = false,
                            X = 17,
                            Y = 7
                        },
                        new
                        {
                            Id = 156,
                            IsOccupied = false,
                            X = 18,
                            Y = 7
                        },
                        new
                        {
                            Id = 157,
                            IsOccupied = false,
                            X = 19,
                            Y = 7
                        },
                        new
                        {
                            Id = 158,
                            IsOccupied = false,
                            X = 20,
                            Y = 7
                        },
                        new
                        {
                            Id = 159,
                            IsOccupied = false,
                            X = 21,
                            Y = 7
                        },
                        new
                        {
                            Id = 160,
                            IsOccupied = false,
                            X = 22,
                            Y = 7
                        },
                        new
                        {
                            Id = 161,
                            IsOccupied = false,
                            X = 23,
                            Y = 7
                        },
                        new
                        {
                            Id = 162,
                            IsOccupied = false,
                            X = 1,
                            Y = 8
                        },
                        new
                        {
                            Id = 163,
                            IsOccupied = false,
                            X = 2,
                            Y = 8
                        },
                        new
                        {
                            Id = 164,
                            IsOccupied = false,
                            X = 3,
                            Y = 8
                        },
                        new
                        {
                            Id = 165,
                            IsOccupied = false,
                            X = 4,
                            Y = 8
                        },
                        new
                        {
                            Id = 166,
                            IsOccupied = false,
                            X = 5,
                            Y = 8
                        },
                        new
                        {
                            Id = 167,
                            IsOccupied = false,
                            X = 6,
                            Y = 8
                        },
                        new
                        {
                            Id = 168,
                            IsOccupied = false,
                            X = 7,
                            Y = 8
                        },
                        new
                        {
                            Id = 169,
                            IsOccupied = false,
                            X = 8,
                            Y = 8
                        },
                        new
                        {
                            Id = 170,
                            IsOccupied = false,
                            X = 9,
                            Y = 8
                        },
                        new
                        {
                            Id = 171,
                            IsOccupied = false,
                            X = 10,
                            Y = 8
                        },
                        new
                        {
                            Id = 172,
                            IsOccupied = false,
                            X = 11,
                            Y = 8
                        },
                        new
                        {
                            Id = 173,
                            IsOccupied = false,
                            X = 12,
                            Y = 8
                        },
                        new
                        {
                            Id = 174,
                            IsOccupied = false,
                            X = 13,
                            Y = 8
                        },
                        new
                        {
                            Id = 175,
                            IsOccupied = false,
                            X = 14,
                            Y = 8
                        },
                        new
                        {
                            Id = 176,
                            IsOccupied = false,
                            X = 15,
                            Y = 8
                        },
                        new
                        {
                            Id = 177,
                            IsOccupied = false,
                            X = 16,
                            Y = 8
                        },
                        new
                        {
                            Id = 178,
                            IsOccupied = false,
                            X = 17,
                            Y = 8
                        },
                        new
                        {
                            Id = 179,
                            IsOccupied = false,
                            X = 18,
                            Y = 8
                        },
                        new
                        {
                            Id = 180,
                            IsOccupied = false,
                            X = 19,
                            Y = 8
                        },
                        new
                        {
                            Id = 181,
                            IsOccupied = false,
                            X = 20,
                            Y = 8
                        },
                        new
                        {
                            Id = 182,
                            IsOccupied = false,
                            X = 21,
                            Y = 8
                        },
                        new
                        {
                            Id = 183,
                            IsOccupied = false,
                            X = 22,
                            Y = 8
                        },
                        new
                        {
                            Id = 184,
                            IsOccupied = false,
                            X = 23,
                            Y = 8
                        },
                        new
                        {
                            Id = 185,
                            IsOccupied = false,
                            X = 1,
                            Y = 9
                        },
                        new
                        {
                            Id = 186,
                            IsOccupied = false,
                            X = 2,
                            Y = 9
                        },
                        new
                        {
                            Id = 187,
                            IsOccupied = false,
                            X = 3,
                            Y = 9
                        },
                        new
                        {
                            Id = 188,
                            IsOccupied = false,
                            X = 4,
                            Y = 9
                        },
                        new
                        {
                            Id = 189,
                            IsOccupied = false,
                            X = 5,
                            Y = 9
                        },
                        new
                        {
                            Id = 190,
                            IsOccupied = false,
                            X = 6,
                            Y = 9
                        },
                        new
                        {
                            Id = 191,
                            IsOccupied = false,
                            X = 7,
                            Y = 9
                        },
                        new
                        {
                            Id = 192,
                            IsOccupied = false,
                            X = 8,
                            Y = 9
                        },
                        new
                        {
                            Id = 193,
                            IsOccupied = false,
                            X = 9,
                            Y = 9
                        },
                        new
                        {
                            Id = 194,
                            IsOccupied = false,
                            X = 10,
                            Y = 9
                        },
                        new
                        {
                            Id = 195,
                            IsOccupied = false,
                            X = 11,
                            Y = 9
                        },
                        new
                        {
                            Id = 196,
                            IsOccupied = false,
                            X = 12,
                            Y = 9
                        },
                        new
                        {
                            Id = 197,
                            IsOccupied = false,
                            X = 13,
                            Y = 9
                        },
                        new
                        {
                            Id = 198,
                            IsOccupied = false,
                            X = 14,
                            Y = 9
                        },
                        new
                        {
                            Id = 199,
                            IsOccupied = false,
                            X = 15,
                            Y = 9
                        },
                        new
                        {
                            Id = 200,
                            IsOccupied = false,
                            X = 16,
                            Y = 9
                        },
                        new
                        {
                            Id = 201,
                            IsOccupied = false,
                            X = 17,
                            Y = 9
                        },
                        new
                        {
                            Id = 202,
                            IsOccupied = false,
                            X = 18,
                            Y = 9
                        },
                        new
                        {
                            Id = 203,
                            IsOccupied = false,
                            X = 19,
                            Y = 9
                        },
                        new
                        {
                            Id = 204,
                            IsOccupied = false,
                            X = 20,
                            Y = 9
                        },
                        new
                        {
                            Id = 205,
                            IsOccupied = false,
                            X = 21,
                            Y = 9
                        },
                        new
                        {
                            Id = 206,
                            IsOccupied = false,
                            X = 22,
                            Y = 9
                        },
                        new
                        {
                            Id = 207,
                            IsOccupied = false,
                            X = 23,
                            Y = 9
                        },
                        new
                        {
                            Id = 208,
                            IsOccupied = false,
                            X = 1,
                            Y = 10
                        },
                        new
                        {
                            Id = 209,
                            IsOccupied = false,
                            X = 2,
                            Y = 10
                        },
                        new
                        {
                            Id = 210,
                            IsOccupied = false,
                            X = 3,
                            Y = 10
                        },
                        new
                        {
                            Id = 211,
                            IsOccupied = false,
                            X = 4,
                            Y = 10
                        },
                        new
                        {
                            Id = 212,
                            IsOccupied = false,
                            X = 5,
                            Y = 10
                        },
                        new
                        {
                            Id = 213,
                            IsOccupied = false,
                            X = 6,
                            Y = 10
                        },
                        new
                        {
                            Id = 214,
                            IsOccupied = false,
                            X = 7,
                            Y = 10
                        },
                        new
                        {
                            Id = 215,
                            IsOccupied = false,
                            X = 8,
                            Y = 10
                        },
                        new
                        {
                            Id = 216,
                            IsOccupied = false,
                            X = 9,
                            Y = 10
                        },
                        new
                        {
                            Id = 217,
                            IsOccupied = false,
                            X = 10,
                            Y = 10
                        },
                        new
                        {
                            Id = 218,
                            IsOccupied = false,
                            X = 11,
                            Y = 10
                        },
                        new
                        {
                            Id = 219,
                            IsOccupied = false,
                            X = 12,
                            Y = 10
                        },
                        new
                        {
                            Id = 220,
                            IsOccupied = false,
                            X = 13,
                            Y = 10
                        },
                        new
                        {
                            Id = 221,
                            IsOccupied = false,
                            X = 14,
                            Y = 10
                        },
                        new
                        {
                            Id = 222,
                            IsOccupied = false,
                            X = 15,
                            Y = 10
                        },
                        new
                        {
                            Id = 223,
                            IsOccupied = false,
                            X = 16,
                            Y = 10
                        },
                        new
                        {
                            Id = 224,
                            IsOccupied = false,
                            X = 17,
                            Y = 10
                        },
                        new
                        {
                            Id = 225,
                            IsOccupied = false,
                            X = 18,
                            Y = 10
                        },
                        new
                        {
                            Id = 226,
                            IsOccupied = false,
                            X = 19,
                            Y = 10
                        },
                        new
                        {
                            Id = 227,
                            IsOccupied = false,
                            X = 20,
                            Y = 10
                        },
                        new
                        {
                            Id = 228,
                            IsOccupied = false,
                            X = 21,
                            Y = 10
                        },
                        new
                        {
                            Id = 229,
                            IsOccupied = false,
                            X = 22,
                            Y = 10
                        },
                        new
                        {
                            Id = 230,
                            IsOccupied = false,
                            X = 23,
                            Y = 10
                        },
                        new
                        {
                            Id = 231,
                            IsOccupied = false,
                            X = 1,
                            Y = 11
                        },
                        new
                        {
                            Id = 232,
                            IsOccupied = false,
                            X = 2,
                            Y = 11
                        },
                        new
                        {
                            Id = 233,
                            IsOccupied = false,
                            X = 3,
                            Y = 11
                        },
                        new
                        {
                            Id = 234,
                            IsOccupied = false,
                            X = 4,
                            Y = 11
                        },
                        new
                        {
                            Id = 235,
                            IsOccupied = false,
                            X = 5,
                            Y = 11
                        },
                        new
                        {
                            Id = 236,
                            IsOccupied = false,
                            X = 6,
                            Y = 11
                        },
                        new
                        {
                            Id = 237,
                            IsOccupied = false,
                            X = 7,
                            Y = 11
                        },
                        new
                        {
                            Id = 238,
                            IsOccupied = false,
                            X = 8,
                            Y = 11
                        },
                        new
                        {
                            Id = 239,
                            IsOccupied = false,
                            X = 9,
                            Y = 11
                        },
                        new
                        {
                            Id = 240,
                            IsOccupied = false,
                            X = 10,
                            Y = 11
                        },
                        new
                        {
                            Id = 241,
                            IsOccupied = false,
                            X = 11,
                            Y = 11
                        },
                        new
                        {
                            Id = 242,
                            IsOccupied = false,
                            X = 12,
                            Y = 11
                        },
                        new
                        {
                            Id = 243,
                            IsOccupied = false,
                            X = 13,
                            Y = 11
                        },
                        new
                        {
                            Id = 244,
                            IsOccupied = false,
                            X = 14,
                            Y = 11
                        },
                        new
                        {
                            Id = 245,
                            IsOccupied = false,
                            X = 15,
                            Y = 11
                        },
                        new
                        {
                            Id = 246,
                            IsOccupied = false,
                            X = 16,
                            Y = 11
                        },
                        new
                        {
                            Id = 247,
                            IsOccupied = false,
                            X = 17,
                            Y = 11
                        },
                        new
                        {
                            Id = 248,
                            IsOccupied = false,
                            X = 18,
                            Y = 11
                        },
                        new
                        {
                            Id = 249,
                            IsOccupied = false,
                            X = 19,
                            Y = 11
                        },
                        new
                        {
                            Id = 250,
                            IsOccupied = false,
                            X = 20,
                            Y = 11
                        },
                        new
                        {
                            Id = 251,
                            IsOccupied = false,
                            X = 21,
                            Y = 11
                        },
                        new
                        {
                            Id = 252,
                            IsOccupied = false,
                            X = 22,
                            Y = 11
                        },
                        new
                        {
                            Id = 253,
                            IsOccupied = false,
                            X = 23,
                            Y = 11
                        },
                        new
                        {
                            Id = 254,
                            IsOccupied = false,
                            X = 1,
                            Y = 12
                        },
                        new
                        {
                            Id = 255,
                            IsOccupied = false,
                            X = 2,
                            Y = 12
                        },
                        new
                        {
                            Id = 256,
                            IsOccupied = false,
                            X = 3,
                            Y = 12
                        },
                        new
                        {
                            Id = 257,
                            IsOccupied = false,
                            X = 4,
                            Y = 12
                        },
                        new
                        {
                            Id = 258,
                            IsOccupied = false,
                            X = 5,
                            Y = 12
                        },
                        new
                        {
                            Id = 259,
                            IsOccupied = false,
                            X = 6,
                            Y = 12
                        },
                        new
                        {
                            Id = 260,
                            IsOccupied = false,
                            X = 7,
                            Y = 12
                        },
                        new
                        {
                            Id = 261,
                            IsOccupied = false,
                            X = 8,
                            Y = 12
                        },
                        new
                        {
                            Id = 262,
                            IsOccupied = false,
                            X = 9,
                            Y = 12
                        },
                        new
                        {
                            Id = 263,
                            IsOccupied = false,
                            X = 10,
                            Y = 12
                        },
                        new
                        {
                            Id = 264,
                            IsOccupied = false,
                            X = 11,
                            Y = 12
                        },
                        new
                        {
                            Id = 265,
                            IsOccupied = false,
                            X = 12,
                            Y = 12
                        },
                        new
                        {
                            Id = 266,
                            IsOccupied = false,
                            X = 13,
                            Y = 12
                        },
                        new
                        {
                            Id = 267,
                            IsOccupied = false,
                            X = 14,
                            Y = 12
                        },
                        new
                        {
                            Id = 268,
                            IsOccupied = false,
                            X = 15,
                            Y = 12
                        },
                        new
                        {
                            Id = 269,
                            IsOccupied = false,
                            X = 16,
                            Y = 12
                        },
                        new
                        {
                            Id = 270,
                            IsOccupied = false,
                            X = 17,
                            Y = 12
                        },
                        new
                        {
                            Id = 271,
                            IsOccupied = false,
                            X = 18,
                            Y = 12
                        },
                        new
                        {
                            Id = 272,
                            IsOccupied = false,
                            X = 19,
                            Y = 12
                        },
                        new
                        {
                            Id = 273,
                            IsOccupied = false,
                            X = 20,
                            Y = 12
                        },
                        new
                        {
                            Id = 274,
                            IsOccupied = false,
                            X = 21,
                            Y = 12
                        },
                        new
                        {
                            Id = 275,
                            IsOccupied = false,
                            X = 22,
                            Y = 12
                        },
                        new
                        {
                            Id = 276,
                            IsOccupied = false,
                            X = 23,
                            Y = 12
                        },
                        new
                        {
                            Id = 277,
                            IsOccupied = false,
                            X = 1,
                            Y = 13
                        },
                        new
                        {
                            Id = 278,
                            IsOccupied = false,
                            X = 2,
                            Y = 13
                        },
                        new
                        {
                            Id = 279,
                            IsOccupied = false,
                            X = 3,
                            Y = 13
                        },
                        new
                        {
                            Id = 280,
                            IsOccupied = false,
                            X = 4,
                            Y = 13
                        },
                        new
                        {
                            Id = 281,
                            IsOccupied = false,
                            X = 5,
                            Y = 13
                        },
                        new
                        {
                            Id = 282,
                            IsOccupied = false,
                            X = 6,
                            Y = 13
                        },
                        new
                        {
                            Id = 283,
                            IsOccupied = false,
                            X = 7,
                            Y = 13
                        },
                        new
                        {
                            Id = 284,
                            IsOccupied = false,
                            X = 8,
                            Y = 13
                        },
                        new
                        {
                            Id = 285,
                            IsOccupied = false,
                            X = 9,
                            Y = 13
                        },
                        new
                        {
                            Id = 286,
                            IsOccupied = false,
                            X = 10,
                            Y = 13
                        },
                        new
                        {
                            Id = 287,
                            IsOccupied = false,
                            X = 11,
                            Y = 13
                        },
                        new
                        {
                            Id = 288,
                            IsOccupied = false,
                            X = 12,
                            Y = 13
                        },
                        new
                        {
                            Id = 289,
                            IsOccupied = false,
                            X = 13,
                            Y = 13
                        },
                        new
                        {
                            Id = 290,
                            IsOccupied = false,
                            X = 14,
                            Y = 13
                        },
                        new
                        {
                            Id = 291,
                            IsOccupied = false,
                            X = 15,
                            Y = 13
                        },
                        new
                        {
                            Id = 292,
                            IsOccupied = false,
                            X = 16,
                            Y = 13
                        },
                        new
                        {
                            Id = 293,
                            IsOccupied = false,
                            X = 17,
                            Y = 13
                        },
                        new
                        {
                            Id = 294,
                            IsOccupied = false,
                            X = 18,
                            Y = 13
                        },
                        new
                        {
                            Id = 295,
                            IsOccupied = false,
                            X = 19,
                            Y = 13
                        },
                        new
                        {
                            Id = 296,
                            IsOccupied = false,
                            X = 20,
                            Y = 13
                        },
                        new
                        {
                            Id = 297,
                            IsOccupied = false,
                            X = 21,
                            Y = 13
                        },
                        new
                        {
                            Id = 298,
                            IsOccupied = false,
                            X = 22,
                            Y = 13
                        },
                        new
                        {
                            Id = 299,
                            IsOccupied = false,
                            X = 23,
                            Y = 13
                        },
                        new
                        {
                            Id = 300,
                            IsOccupied = false,
                            X = 1,
                            Y = 14
                        },
                        new
                        {
                            Id = 301,
                            IsOccupied = false,
                            X = 2,
                            Y = 14
                        },
                        new
                        {
                            Id = 302,
                            IsOccupied = false,
                            X = 3,
                            Y = 14
                        },
                        new
                        {
                            Id = 303,
                            IsOccupied = false,
                            X = 4,
                            Y = 14
                        },
                        new
                        {
                            Id = 304,
                            IsOccupied = false,
                            X = 5,
                            Y = 14
                        },
                        new
                        {
                            Id = 305,
                            IsOccupied = false,
                            X = 6,
                            Y = 14
                        },
                        new
                        {
                            Id = 306,
                            IsOccupied = false,
                            X = 7,
                            Y = 14
                        },
                        new
                        {
                            Id = 307,
                            IsOccupied = false,
                            X = 8,
                            Y = 14
                        },
                        new
                        {
                            Id = 308,
                            IsOccupied = false,
                            X = 9,
                            Y = 14
                        },
                        new
                        {
                            Id = 309,
                            IsOccupied = false,
                            X = 10,
                            Y = 14
                        },
                        new
                        {
                            Id = 310,
                            IsOccupied = false,
                            X = 11,
                            Y = 14
                        },
                        new
                        {
                            Id = 311,
                            IsOccupied = false,
                            X = 12,
                            Y = 14
                        },
                        new
                        {
                            Id = 312,
                            IsOccupied = false,
                            X = 13,
                            Y = 14
                        },
                        new
                        {
                            Id = 313,
                            IsOccupied = false,
                            X = 14,
                            Y = 14
                        },
                        new
                        {
                            Id = 314,
                            IsOccupied = false,
                            X = 15,
                            Y = 14
                        },
                        new
                        {
                            Id = 315,
                            IsOccupied = false,
                            X = 16,
                            Y = 14
                        },
                        new
                        {
                            Id = 316,
                            IsOccupied = false,
                            X = 17,
                            Y = 14
                        },
                        new
                        {
                            Id = 317,
                            IsOccupied = false,
                            X = 18,
                            Y = 14
                        },
                        new
                        {
                            Id = 318,
                            IsOccupied = false,
                            X = 19,
                            Y = 14
                        },
                        new
                        {
                            Id = 319,
                            IsOccupied = false,
                            X = 20,
                            Y = 14
                        },
                        new
                        {
                            Id = 320,
                            IsOccupied = false,
                            X = 21,
                            Y = 14
                        },
                        new
                        {
                            Id = 321,
                            IsOccupied = false,
                            X = 22,
                            Y = 14
                        },
                        new
                        {
                            Id = 322,
                            IsOccupied = false,
                            X = 23,
                            Y = 14
                        });
                });

            modelBuilder.Entity("WebProject.Models.Land", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
